DROP INDEX "titlesearch_idx"
DROP INDEX "abstractsearch_idx"
DROP INDEX "alltextsearch_idx"
DROP TABLE "pages"
DROP TABLE "spreadsheet_files"
DROP TABLE "entry_files"
DROP TABLE "temp_insert_entries"
DROP TABLE "entries"
