// https://dbml.dbdiagram.io/docs

Table entries {
  id text [primary key]
  url text
  entry_type text
  entry_language text
  languages text[]
  regions text[]
  start_date date
  end_date date
  alternates text[]
  related text[]

  title text
  authors text[]
  abstract text
  keywords text[]

  org text
  org_doc_id text
  org_type text
  youth_led text
  notes text

  // not needed
  // refered_to_by text
  // refers_to text
  // ra text
}

Table entry_files {
  entry_id text [ref: > entries.id]
  filename text
  url text

  indexes {
    (entry_id, filename) [pk]
  }
}

Table spreadsheet_files {
  id text [primary key]
  filename text
  url text
  added_at timestamp
}

Table pages {
  id text [primary key]
  content text [not null, default: 'This is a sample page. Login to edit it.']
  google_form_id text [not null, default: '']
  updated_at timestamp [not null, default: `now()`]
}
